language: php
php:
  - "5.5"
before_script:
  - composer install --dev --no-interaction
  - cp app/Config/core.example.php app/Config/core.php
  - cp app/Config/database.travis.php app/Config/database.php
  - cp app/Config/oauth.example.php app/Config/oauth.php
  - mysql -e 'create database pmaerr;'
script:
  - app/Console/cake Migrations.migration run all -p Migrations
  - app/Console/cake Migrations.migration run all --precheck Migrations.PrecheckCondition
  - app/Console/cake test app AllTests --coverage-clover build/logs/clover.xml --configuration=phpunit.xml
after_script:
  - php vendor/bin/coveralls -v
