language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - nightly
sudo: false
before_script:
  - cp config/app_travis.php config/app.php
  - cp config/oauth_example.php config/oauth.php
  - mysql -e 'create database pmaerr;'
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install
script:
  - bin/cake migrations migrate
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml -c phpunit.xml.dist
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
